spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo
    username: demo
    password: "demo"
    pool:
      initial-size: 3
      max-size: 10
      max-idle-time: 30m
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/demo
    user: demo
    password: "demo"
    change-log: classpath:db/changelog/db.changelog-master.xml