version: '3'
services:
  postgres:
    image: postgres:11
    container_name: demo-db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - 5432:5432